server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8


spring:
  datasource:
    url : jdbc:mysql://localhost:3306/vuedemo?useSSL=false
    username : root
    password : 123456qwer
    driverClassName : com.mysql.jdbc.Driver
    thymeleaf:
    cache: false


